Vagrant.configure('2') do |config|    
	
	config.vm.box = "debian/bullseye64"
	config.vm.box_check_update = false
  config.disksize.size = "20GB"
	config.vm.provider "virtualbox" do |vb|  
      #vb.gui = true
      vb.memory = "2048"
    end

    config.vm.network "private_network", ip: "192.168.33.10"
	

end